from app.models.usuario import Usuario
from app.models.vehiculo import Vehiculo
from app.models.taller import Taller
from app.models.tecnico import Tecnico
from app.models.incidente import Incidente
from app.models.evidencia import Evidencia
from app.models.asignacion import Asignacion
from app.models.pago import Pago
from app.models.notificacion import Notificacion
from app.models.historial_estado import HistorialEstado
from app.models.calificacion import Calificacion
from app.models.metrica_taller import MetricaTaller